-- Require individual plugin configurations and append them to the 'lvim.plugins' table
table.insert(lvim.plugins, require("ben.plugins.colorschemes"))
table.insert(lvim.plugins, require("ben.plugins.autotag"))
table.insert(lvim.plugins, require("ben.plugins.copilot"))
table.insert(lvim.plugins, require("ben.plugins.noice"))
table.insert(lvim.plugins, require("ben.plugins.neoscroll"))
table.insert(lvim.plugins, require("ben.plugins.wakatime"))
table.insert(lvim.plugins, require("ben.plugins.numb"))
table.insert(lvim.plugins, require("ben.plugins.endwise"))
table.insert(lvim.plugins, require("ben.plugins.tmux-navigator"))
table.insert(lvim.plugins, require("ben.plugins.blame"))
table.insert(lvim.plugins, require("ben.plugins.base16"))
